"""identity_tables"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("target_github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'MEMBER'"), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'ACCEPTED' AND accepted_at IS NOT NULL AND accepted_by IS NOT NULL) OR "
            "(status <> 'ACCEPTED' AND accepted_at IS NULL AND accepted_by IS NULL)",
            name="ck_invitations_acceptance",
        ),
        sa.CheckConstraint(
            "(status = 'REVOKED') = (revoked_at IS NOT NULL)", name="ck_invitations_revocation"
        ),
        sa.CheckConstraint("role IN ('MEMBER', 'ADMIN')", name="ck_invitations_role"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')", name="ck_invitations_status"
        ),
        sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name="ck_invitations_token_hash"),
        sa.CheckConstraint("expires_at > created_at", name="ck_invitations_expiry"),
        sa.CheckConstraint(
            "target_github_user_id > 0", name="ck_invitations_target_github_user_id_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_invitations_token_hash"),
    )
    op.create_index(
        "ix_invitations_pending_expiry",
        "invitations",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        "uq_invitations_pending_target",
        "invitations",
        ["workspace_id", "target_github_user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("browser_binding_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("return_path", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(purpose = 'OAUTH_LOGIN' AND user_id IS NULL AND workspace_id IS NULL) OR "
            "(purpose = 'GITHUB_INSTALL' AND user_id IS NOT NULL AND workspace_id IS NOT NULL)",
            name="ck_login_attempts_binding",
        ),
        sa.CheckConstraint(
            "browser_binding_hash ~ '^[0-9a-f]{64}$'", name="ck_login_attempts_browser_binding_hash"
        ),
        sa.CheckConstraint(
            "purpose IN ('OAUTH_LOGIN', 'GITHUB_INSTALL')", name="ck_login_attempts_purpose"
        ),
        sa.CheckConstraint("state_hash ~ '^[0-9a-f]{64}$'", name="ck_login_attempts_state_hash"),
        sa.CheckConstraint("expires_at > created_at", name="ck_login_attempts_expiry"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash", name="uq_login_attempts_state_hash"),
    )
    op.create_index("ix_login_attempts_expires_at", "login_attempts", ["expires_at"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name="ck_refresh_sessions_token_hash"),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoke_reason IS NULL)",
            name="ck_refresh_sessions_revocation_pair",
        ),
        sa.CheckConstraint(
            "(rotated_at IS NULL) = (replaced_by_id IS NULL)",
            name="ck_refresh_sessions_rotation_pair",
        ),
        sa.CheckConstraint("expires_at > created_at", name="ck_refresh_sessions_expiry"),
        sa.CheckConstraint(
            "replaced_by_id IS NULL OR replaced_by_id <> id",
            name="ck_refresh_sessions_no_self_replacement",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_sessions_token_hash"),
    )
    op.create_index(
        "ix_refresh_sessions_expires_at", "refresh_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_refresh_sessions_user_family",
        "refresh_sessions",
        ["user_id", "family_id"],
        unique=False,
    )
    op.create_index(
        "uq_refresh_sessions_replaced_by_id",
        "refresh_sessions",
        ["replaced_by_id"],
        unique=True,
        postgresql_where=sa.text("replaced_by_id IS NOT NULL"),
    )
    op.create_table(
        "users",
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name="ck_users_status"),
        sa.CheckConstraint("github_user_id > 0", name="ck_users_github_user_id_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_user_id", name="uq_users_github_user_id"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND ended_at IS NULL) OR "
            "(status IN ('LEFT', 'REMOVED') AND ended_at IS NOT NULL)",
            name="ck_workspace_members_ended_at",
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'ADMIN', 'MEMBER')", name="ck_workspace_members_role"
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'LEFT', 'REMOVED')", name="ck_workspace_members_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_workspace_members_workspace_user"),
    )
    op.create_index(
        "ix_workspace_members_user_status",
        "workspace_members",
        ["user_id", "status", "workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_workspace_members_workspace_status",
        "workspace_members",
        ["workspace_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "uq_workspace_members_active_owner",
        "workspace_members",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("role = 'OWNER' AND status = 'ACTIVE'"),
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_workspaces_name_nonblank"),
        sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name="ck_workspaces_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workspaces_creator_created",
        "workspaces",
        ["created_by", sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Destructive: removes identity data; use only in an empty dedicated test DB."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workspaces_creator_created", table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(
        "uq_workspace_members_active_owner",
        table_name="workspace_members",
        postgresql_where=sa.text("role = 'OWNER' AND status = 'ACTIVE'"),
    )
    op.drop_index("ix_workspace_members_workspace_status", table_name="workspace_members")
    op.drop_index("ix_workspace_members_user_status", table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_table("users")
    op.drop_index(
        "uq_refresh_sessions_replaced_by_id",
        table_name="refresh_sessions",
        postgresql_where=sa.text("replaced_by_id IS NOT NULL"),
    )
    op.drop_index("ix_refresh_sessions_user_family", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_expires_at", table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index("ix_login_attempts_expires_at", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index(
        "uq_invitations_pending_target",
        table_name="invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        "ix_invitations_pending_expiry",
        table_name="invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("invitations")
    # ### end Alembic commands ###
