"""Repository, immutable config, PR metadata and durable sync jobs. No physical FKs."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_login", sa.String(length=255), nullable=False),
        sa.Column("repository_name", sa.String(length=255), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("default_branch", sa.String(length=1024), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column(
            "connection_generation", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("current_config_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "auto_analysis_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("ai_mode", sa.String(length=24), server_default=sa.text("'OFF'"), nullable=False),
        sa.Column("ai_policy_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("ai_policy_changed_by", sa.Uuid(), nullable=True),
        sa.Column("connected_by", sa.Uuid(), nullable=False),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'DISCONNECTED') = (disconnected_at IS NOT NULL)",
            name="ck_repository_disconnected",
        ),
        sa.CheckConstraint("ai_mode IN ('OFF','FINDINGS_ONLY')", name="ck_repository_ai_mode"),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','DISCONNECTED')", name="ck_repository_status"
        ),
        sa.CheckConstraint(
            "connection_generation > 0 AND ai_policy_version > 0", name="ck_repository_versions"
        ),
        sa.CheckConstraint(
            "github_repository_id > 0 AND installation_id > 0", name="ck_repository_github_ids"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "github_repository_id", name="uq_repository_workspace_github"
        ),
    )
    op.create_index(
        "ix_repository_workspace_status",
        "repository_connections",
        ["workspace_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "uq_repository_active_github",
        "repository_connections",
        ["github_repository_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE','SUSPENDED')"),
    )
    op.create_index(
        "ix_repository_installation_status",
        "repository_connections",
        ["installation_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "ix_repository_config",
        "repository_connections",
        ["current_config_version_id"],
        unique=False,
    )
    op.create_table(
        "rule_config_versions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("repository_connection_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "layer_mappings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "ignored_paths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "auto_analysis_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("ai_mode", sa.String(length=24), server_default=sa.text("'OFF'"), nullable=False),
        sa.Column("config_digest", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ai_mode IN ('OFF','FINDINGS_ONLY')", name="ck_config_ai_mode"),
        sa.CheckConstraint("config_digest ~ '^[0-9a-f]{64}$'", name="ck_config_digest"),
        sa.CheckConstraint(
            "jsonb_typeof(rules)='object' AND jsonb_typeof(layer_mappings)='object' AND jsonb_typeof(ignored_paths)='array'",  # noqa: E501
            name="ck_config_json",
        ),
        sa.CheckConstraint("version > 0 AND schema_version > 0", name="ck_config_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_connection_id", "version", name="uq_config_repository_version"
        ),
    )
    op.create_index(
        "ix_config_workspace_repository",
        "rule_config_versions",
        ["workspace_id", "repository_connection_id", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_table(
        "pull_requests",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("repository_connection_id", sa.Uuid(), nullable=False),
        sa.Column("github_pr_id", sa.BigInteger(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author_github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("author_login", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "merge_status",
            sa.String(length=16),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("base_ref", sa.String(length=1024), nullable=True),
        sa.Column("head_ref", sa.String(length=1024), nullable=True),
        sa.Column("base_sha", sa.String(length=64), nullable=True),
        sa.Column("head_sha", sa.String(length=64), nullable=True),
        sa.Column("changed_files_count", sa.Integer(), nullable=True),
        sa.Column("commits_count", sa.Integer(), nullable=True),
        sa.Column("github_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("github_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_connection_generation", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$' AND head_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",  # noqa: E501
            name="ck_pr_shas",
        ),
        sa.CheckConstraint(
            "state IN ('OPEN','CLOSED') AND merge_status IN ('UNKNOWN','NOT_MERGED','MERGED')",
            name="ck_pr_state",
        ),
        sa.CheckConstraint("changed_files_count>=0 AND commits_count>=0", name="ck_pr_counts"),
        sa.CheckConstraint(
            "github_pr_id>0 AND pr_number>0 AND synced_connection_generation>0", name="ck_pr_ids"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_connection_id", "github_pr_id", name="uq_pr_repository_github"
        ),
        sa.UniqueConstraint(
            "repository_connection_id", "pr_number", name="uq_pr_repository_number"
        ),
    )
    op.create_index(
        "ix_pr_workspace_repository_updated",
        "pull_requests",
        [
            "workspace_id",
            "repository_connection_id",
            sa.literal_column("github_updated_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_table(
        "pull_request_sync_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("repository_connection_id", sa.Uuid(), nullable=False),
        sa.Column("connection_generation", sa.Integer(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("requested_pr_number", sa.Integer(), nullable=True),
        sa.Column("request_cursor", sa.String(length=1024), nullable=True),
        sa.Column("next_cursor", sa.String(length=1024), nullable=True),
        sa.Column("etag", sa.String(length=512), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("fetched_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(actor_type='USER' AND requested_by IS NOT NULL) OR (actor_type='SYSTEM' AND requested_by IS NULL)",  # noqa: E501
            name="ck_sync_actor",
        ),
        sa.CheckConstraint(
            "(mode='SINGLE' AND requested_pr_number>0 AND request_cursor IS NULL) OR (mode='RECENT' AND requested_pr_number IS NULL AND request_cursor IS NULL) OR (mode='PAGE' AND requested_pr_number IS NULL AND request_cursor IS NOT NULL)",  # noqa: E501
            name="ck_sync_mode",
        ),
        sa.CheckConstraint(
            "(status IN ('COMPLETED','FAILED','CANCELED')) = (finished_at IS NOT NULL)",
            name="ck_sync_finished",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELED')", name="ck_sync_status"
        ),
        sa.CheckConstraint("connection_generation>0 AND fetched_count>=0", name="ck_sync_counts"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_finished",
        "pull_request_sync_runs",
        ["finished_at"],
        unique=False,
        postgresql_where=sa.text("finished_at IS NOT NULL"),
    )
    op.create_index(
        "ix_sync_workspace_repository_created",
        "pull_request_sync_runs",
        [
            "workspace_id",
            "repository_connection_id",
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "uq_sync_active_repository",
        "pull_request_sync_runs",
        ["repository_connection_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','RUNNING')"),
    )
    op.create_table(
        "jobs",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), server_default=sa.text("'READY'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_generation", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "attempt_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state IN ('SUCCEEDED','DEAD','CANCELED')) = (completed_at IS NOT NULL)",
            name="ck_job_completed",
        ),
        sa.CheckConstraint(
            "(state='LEASED' AND lease_until IS NOT NULL AND claimed_by IS NOT NULL) OR (state<>'LEASED' AND lease_until IS NULL AND claimed_by IS NULL)",  # noqa: E501
            name="ck_job_lease",
        ),
        sa.CheckConstraint(
            "dedupe_key ~ '^[0-9a-f]{64}$' AND jsonb_typeof(attempt_history)='array'",
            name="ck_job_payload",
        ),
        sa.CheckConstraint(
            "kind IN ('SYNC_PULL_REQUESTS','ANALYZE_PR','EXPLAIN_FINDINGS','PROCESS_WEBHOOK')",
            name="ck_job_kind",
        ),
        sa.CheckConstraint(
            "state IN ('READY','LEASED','SUCCEEDED','DEAD','CANCELED')", name="ck_job_state"
        ),
        sa.CheckConstraint(
            "workspace_id IS NOT NULL OR kind='PROCESS_WEBHOOK'", name="ck_job_workspace"
        ),
        sa.CheckConstraint(
            "attempts>=0 AND attempts<=max_attempts AND max_attempts>0 AND lease_generation>=0",
            name="ck_job_attempts",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_job_dedupe"),
        sa.UniqueConstraint("kind", "aggregate_id", name="uq_job_aggregate"),
    )
    op.create_index(
        "ix_job_leased",
        "jobs",
        ["lease_until", "id"],
        unique=False,
        postgresql_where=sa.text("state='LEASED'"),
    )
    op.create_index(
        "ix_job_completed",
        "jobs",
        ["completed_at"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NOT NULL"),
    )
    op.create_index(
        "ix_job_ready",
        "jobs",
        ["available_at", "id"],
        unique=False,
        postgresql_where=sa.text("state='READY'"),
    )
    op.create_index(
        "ix_job_workspace_state",
        "jobs",
        ["workspace_id", "state", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("jobs")
    op.drop_table("pull_request_sync_runs")
    op.drop_table("pull_requests")
    op.drop_table("rule_config_versions")
    op.drop_table("repository_connections")
